name: Gerar APK Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar EAS CLI
        run: npm install -g eas-cli

      - name: Instalar dependências
        run: npm install

      - name: Gerar APK Localmente
        run: npx eas-cli build --platform android --profile preview --local --output ./reuse.apk

      - name: Salvar APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: Reuse-APK
          path: ./reuse.apk
